### PR TITLE
Fix wrong formatting of Common Data Objects headline

### PR DESCRIPTION
**Pull request by fmueller**
For some unknown reason headline of common data objects is not formatted in http://zalando.github.io/restful-api-guidelines/common-data-objects/CommonDataObjects.html

This change will fix it.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
What's the difference? Looks 100% identical to me :eyes:

**Comment by whiskeysierra** [comment]
:+1:

**Comment by fmueller** [comment]
Must be some weird unicode encoding problem. This line was also not marked as headline in my markdown editor. After I removed it and retyped it, everything was fine.

**Comment by ePaul** [comment]
:+1:

**Comment by ePaul** [comment]
:+1:

**Comment by whiskeysierra** [comment]
:+1:

**Pull request merged**
