### PR TITLE
Fixed link in compatibility.adoc

### PR DESCRIPTION
**Pull request by munterbusch-ms**
Seems linked blog post moved.

### CODE REVIEW

**Comment by rishiraj88** [comment]
Thanks, @munterbusch-ms !

**Comment by ePaul** [comment]
:+1:

**Comment by tkrop** [comment]
👍

**Comment by ePaul** [comment]
Thanks!

**Comment by rishiraj88** [comment]
https://apisyouwonthate.com/blog/api-versioning-has-no-right-way

works fine.

Thanks!

**Pull request merged**
