### PR TITLE
Add empty lines between chapter includes

### LINKED ISSUE #703: Appendix is not rendered properly
The `References` section is not being rendered properly. See screenshots below:

Web Version:
web version

PDF version:
pdf version

### PR DESCRIPTION
**Pull request by ePaul**
The title of the first appendix, titled "References", is not properly rendered (and does not appear in the table of contents).
Adding an empty line before it seems to help.

Fixes #703.

### CODE REVIEW

**Comment by tkrop** [comment]
@ePaul yes, true. I have fixed similar issues before multiple time. The problem is that asciidoc does not automatically added empty lines between includes. The opposite, asciidoc documentation suggests to add emtpy lines between includes if needed and to not rely on empty lines in the chapter files.

May be we should fix this once and for all and add empty lines between the include directives as suggested.

**Comment by ePaul** [comment]
Okay, I will do that instead.

**Comment by ePaul** [comment]
:+1:

**Comment by tfrauenstein** [comment]
👍

**Pull request merged**
