### PR TITLE
Fix: the api id header is x-api-id, not x-id.

### PR DESCRIPTION
**Pull request by ioggstream**
### what does this PR do

Fix the api-id header name.

### I expect

The api-id header to be x-api-id

### instead

The api-id header is x-id

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
Thanks!

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by ePaul** [comment]
:+1:

**Comment by ioggstream** [comment]
Thanks! You've been very fast!

Are you working on openapi-v3 too? 

Thx again + Peace,
R.

**Pull request merged**
