### PR TITLE
clean-up 'internal links'

### PR DESCRIPTION
**Pull request by tfrauenstein**
updated: links to new API Guild docu
editorial: make sure that all internal links are grep-able (i.e. single lined) for easy checks

### CODE REVIEW

**Comment by tkrop** [comment]
@tfrauenstein how about naming all internal links like `:internal-...` and referencing the name instead of the link. This would also make it easier to maintain and list them.

**Comment by tfrauenstein** [comment]
@tkrop thx. for the proposal, but maintenance even would get harder because the internal links vary in link reference + text such that basically each internal link occurance needs to be abstracted via  `internal-..` constant without its re-usage.

**Comment by tkrop** [comment]
@tfrauenstein I didn't mean to include the text in the reference - only the link.

**Comment by tfrauenstein** [comment]
@tkrop ok done, pls. approve

**Comment by ePaul** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Pull request merged**
