### PR TITLE
Event guidelines 

### PR DESCRIPTION
**Pull request by dehora**
- Make it clear that the api supports open api in json format and not just json schema

- Tidy up guidelines on when it's ok for events to not match api resource representations

/ @fmueller @tfrauenstein

### CODE REVIEW

**Comment by tfrauenstein** [comment]
fine, can be merged

**Comment by whiskeysierra** [comment]
@tfrauenstein Approvals need to be a comment with a single :+1: (`:+1:`)

**Comment by whiskeysierra** [comment]
:+1:

**Comment by tfrauenstein** [comment]
👍

**Pull request merged**
