### PR TITLE
Valid url - [REST API Design - Resource Modeling]

### PR DESCRIPTION
**Pull request by p610**
Fix for [REST API Design - Resource Modeling] url.

### CODE REVIEW

**Comment by tfrauenstein** [comment]
👍

**Comment by tkrop** [comment]
@p610 Thanks for contributing unfortunately, we cannot merge until the build is successful, which would require you to update your private branch to merge the latest `main` branch.

**Comment by tkrop** [comment]
:+1:

**Comment by tfrauenstein** [comment]
👍

**Pull request merged**
