### PR TITLE
Added Swagger IntelliJ IDEA Plugin to tooling

### PR DESCRIPTION
**Pull request by semonte**

### CODE REVIEW

**Comment by tfrauenstein** [comment]
👍

**Comment by whiskeysierra** [comment]
:+1:

**Comment by fmueller** [comment]
Due #69 this cannot be merged yet.

**Comment by whiskeysierra** [comment]
@semonte Can you update your branch?

**Comment by semonte** [comment]
Done

**Comment by whiskeysierra** [comment]
:+1:

**Comment by ePaul** [comment]
:+1:

**Pull request merged**
