### PR TITLE
Add more explanation for flow id header

### LINKED ISSUE #92: Give more guidance on generation of flowId header
From my point of view we should give a default implementation for generating the FlowId Header. Just a UUID in Java, for instance. What do you think?

### PR DESCRIPTION
**Pull request by fmueller**
Fixes #92

### CODE REVIEW

**Comment by ePaul** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
@fmueller Very good FlowId explanation! One thing we can add: the `traceability` keyword, since it's the main purpose of this technical concept.

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by fmueller** [comment]
@maxim-tschumak Good hint. I added some words about traceability.

@ePaul @maxim-tschumak Can you please re-check and re-thumb if it is still ok to merge? :)

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by ePaul** [comment]
:+1:

**Pull request merged**
