### PR TITLE
Updated links to REST literature

### PR DESCRIPTION
**Pull request by tfrauenstein**

### CODE REVIEW

**Comment by vadeg** [comment]
👍

**Comment by tkrop** [comment]
How about also adding: https://www.thoughtworks.com/de/insights/blog/rest-api-design-resource-modeling as a new resource here. I'm not sure whether we have mentioned this resource somewhere else, but I think it contributes alot.

**Comment by tkrop** [comment]
:+1:

**Comment by tfrauenstein** [comment]
👍

**Comment by tkrop** [comment]
:+1:

**Pull request merged**
