### PR TITLE
Add Rest Maturity Level 2 rule and rephrasing HATEOAS rule

### PR DESCRIPTION
**Pull request by fmueller**
This change solves #55 and adds more direct guidance to strive for REST Maturity Level 2 instead of Level 3.

### CODE REVIEW

**Comment by tkrop** [comment]
I like you changes. Please go on to merge.

:+1:

**Comment by tkrop** [comment]
:+1:

**Comment by ePaul** [comment]
:+1:

**Comment by hjacobs** [comment]
Finally we put it to rest (for now) :smile:  

> For now, we have not seen a good reason to implement HATEOAS in an API.

**Pull request merged**
