### PR TITLE
Removed semantic versioning for gitbook build

### PR DESCRIPTION
**Pull request by fmueller**
This hopefully solves #69

### CODE REVIEW

**Comment by fmueller** [comment]
@ePaul @whiskeysierra @dehora Need 2 approvals. This will fix our current build issues.

**Comment by ePaul** [comment]
Hmm, I can't really judge if that is good, but I'll trust you here.

:+1:

**Comment by ePaul** [comment]
:+1:

**Comment by whiskeysierra** [comment]
:+1:

**Pull request merged**
