### PR TITLE
Fixing links to common-data-types chapter (#272)

### LINKED ISSUE #272: Broken Links to Common Data Types Chapter
Changes introduced in https://github.com/zalando/restful-api-guidelines/pull/250 have broken the link in the table of contents and some other links in the other chapters.

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Fixes #272.

### CODE REVIEW

**Comment by tkrop** [comment]
Good catch. Thanks.

**Comment by tkrop** [comment]
👍

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by dehora** [comment]
:+1:

**Pull request merged**
