### PR TITLE
Removes private internal Zalando documents.

### PR DESCRIPTION
**Pull request by dehora**
Going ahead with removing private links while https://github.com/zalando/restful-api-guidelines/issues/394 gets resolved.

### CODE REVIEW

**Comment by dehora** [comment]
:+1:

**Comment by whiskeysierra** [comment]
:+1:

**Comment by ddufourboivin-zalando** [comment]
# ⚠️ WARNING / SUGGESTION
We should keep a trace of those internally and prepare a _Companion Document_, with the same format as those guidelines, that indicates what should be read additionally for Zalando employees.

**Comment by dehora** [comment]
> We should keep a trace of those internally and prepare a Companion Document,

@ddufourboivin-zalando might be an idea to open an issue for that or added it to  #394 so it doesn't get lost here

**Comment by dehora** [comment]
:+1:

**Comment by tfrauenstein** [comment]
@dehora I can live with deletion of link 1 - 3 -- they are less relevant for efficient rule application.  However, in the functional naming section we should link to our functional name inventory service (such that teams can efficiently create names). We will add this.

**Pull request merged**
