### PR TITLE
Guidance for GET-with-body documentation

### PR DESCRIPTION
**Pull request by tfrauenstein**
Standardise how GET-with-body hint should be provided as part of the POST endpoint description.
Analog for DELETE-with-body.

### CODE REVIEW

**Comment by otaciliolacerda** [comment]
👍

**Comment by tfrauenstein** [comment]
👍

**Comment by otaciliolacerda** [comment]
👍

**Comment by tkrop** [comment]
@tfrauenstein I'm wondering whether `request body payload` isn't a bit over-specified and hard to read.

**Comment by tfrauenstein** [comment]
@tkrop I think it is ok -- though it is a bit over-specified. Reason: we mostly used `body` so far (and sometimes `payload`) and I think `payload` is the better term -- but I did not deleted `body` due to backward compatibility with `GET-with-Body` references.  Do you know whether acsiidoc supports multiple reference labels? -- than I can do the `body`clean-up:
```
[[get-with-body]]
[[get-with-payload]]
=== GET with payload
```

**Comment by tkrop** [comment]
:+1:

**Comment by tfrauenstein** [comment]
👍

**Pull request merged**
