### PR TITLE
spelling and grammar fixes

### PR DESCRIPTION
**Pull request by tkrop**
fixes #695.

Merges latest structural changes from master on #695 to allow merging.

### CODE REVIEW

**Comment by tfrauenstein** [comment]
👍

**Comment by a1exsh** [comment]
Just spotted this one (catAgories):

image
https://opensource.zalando.com/restful-api-guidelines/#event-categories

**Comment by scop** [comment]
Ah, I did not notice #695 was closed in favour of this one. I just rebased my old branch on top of current master too, and added a few new fixes (including by chance the "catagories" one), my changes are at https://github.com/scop/restful-api-guidelines/commit/1d5325dab23d09e2866d595f6a73e59d222a4f3c.patch

**Comment by sambaranhazra** [comment]
👍

**Comment by scop** [comment]
Missed ones here are in #700

**Pull request merged**
