### PR TITLE
Update general-guidelines.adoc

### PR DESCRIPTION
**Pull request by a-akimov**
Fixed typo and spelling of OpenAPI

### CODE REVIEW

**Comment by tfrauenstein** [comment]
👍

**Comment by tkrop** [comment]
:+1:

**Comment by tkrop** [comment]
Thanks, seems as if only two locations now are left.

**Comment by tkrop** [comment]
@a-akimov while we would like to merge this, we can't since the build failed because of a temporary failure. Can you re-trigger it to make it successful? I unfortunately can't.

**Comment by a-akimov** [comment]
> @a-akimov while we would like to merge this, we can't since the build failed because of a temporary failure. Can you re-trigger it to make it successful? I unfortunately can't.

@tkrop thank you for reviewing. I would love to re-trigger, but not sure how exactly to do this. Or you mean to make another commit and pull request?

**Comment by tkrop** [comment]
should also work.

**Comment by tkrop** [comment]
the simplest way is to do `git commit --amend` on the PR to get this rebuild.

**Comment by ePaul** [comment]
I've retriggered the build in Travis CI's UI.

**Comment by ePaul** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Pull request merged**
