### PR TITLE
MUST use standard data formats (2)

### PR DESCRIPTION
**Pull request by tfrauenstein**
solves https://github.com/zalando/restful-api-guidelines/issues/642 -- replaces outdated https://github.com/zalando/restful-api-guidelines/pull/650

### CODE REVIEW

**Comment by tkrop** [comment]
:+1:

**Comment by vadeg** [comment]
@tfrauenstein could you please update the [changelog](https://github.com/zalando/restful-api-guidelines/blob/master/chapters/changelog.adoc)? For example that _Severity of Rule 238 changed from SHOULD to MUST_.

**Comment by tfrauenstein** [comment]
@vadeg  change log history is now up-to-date, thx.

**Comment by vadeg** [comment]
👍

**Comment by tkrop** [comment]
:+1:

**Pull request merged**
